package javav;
//

// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-05-10 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\FEUP\\4o_Ano\\2o_Semestre\\SCRI\\Variant_Forma_Methods\\TASVariant\\ATOutput.vdmpp".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class ATOutput implements EvaluatePP {

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=ATOutputSentinel KEEP=NO
  class ATOutputSentinel extends Sentinel {

    public final int validate = 0;

    public final int nr_functions = 1;


    public ATOutputSentinel () throws CGException {}


    public ATOutputSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=ATOutputSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new ATOutputSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_ATOutput KEEP=NO
  private void vdm_init_ATOutput () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_ATOutput


// ***** VDMTOOLS START Name=ATOutput KEEP=NO
  public ATOutput () throws CGException {
    vdm_init_ATOutput();
  }
// ***** VDMTOOLS END Name=ATOutput


// ***** VDMTOOLS START Name=validate#1|Number KEEP=NO
  public Boolean validate (final Number res) throws CGException {
    sentinel.entering(((ATOutputSentinel)sentinel).validate);
    try {
      Boolean cond_2 = null;
      if (!(cond_2 = Boolean.valueOf(res.doubleValue() < 0)).booleanValue()) 
        cond_2 = Boolean.valueOf(res.doubleValue() > 1000);
      if (cond_2.booleanValue()) 
        return Boolean.FALSE;
      else 
        return Boolean.TRUE;
    }
    finally {
      sentinel.leaving(((ATOutputSentinel)sentinel).validate);
    }
  }
// ***** VDMTOOLS END Name=validate#1|Number

}
;
