package javav;

//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-05-12 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "D:\\FEUP\\4o_Ano\\2o_Semestre\\SCRI\\Variant_Forma_Methods\\TASVariant/Voter.vdmpp".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.List;
import java.util.ArrayList;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Voter implements EvaluatePP {

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=VoterSentinel KEEP=NO
  class VoterSentinel extends Sentinel {

    public final int vote = 0;

    public final int nr_functions = 1;


    public VoterSentinel () throws CGException {}


    public VoterSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=VoterSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new VoterSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel

// ***** VDMTOOLS START Name=ERROR KEEP=NO
  private static final Number ERROR = new Integer(-1);
// ***** VDMTOOLS END Name=ERROR


// ***** VDMTOOLS START Name=vdm_init_Voter KEEP=NO
  private void vdm_init_Voter () {
    try {
      setSentinel();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Voter


// ***** VDMTOOLS START Name=Voter KEEP=NO
  public Voter () throws CGException {
    vdm_init_Voter();
  }
// ***** VDMTOOLS END Name=Voter


// ***** VDMTOOLS START Name=vote#1|List KEEP=NO
  public Number vote (final List vals) throws CGException {
    sentinel.entering(((VoterSentinel)sentinel).vote);
    try {
      if (vals.size() == 0) {
    	  System.out.println("No vals!");
        return ERROR;
      }
      else 
        return new Double(sum(vals).doubleValue() / (double)vals.size());
    }
    finally {
      sentinel.leaving(((VoterSentinel)sentinel).vote);
    }
  }
// ***** VDMTOOLS END Name=vote#1|List


// ***** VDMTOOLS START Name=sum#1|List KEEP=NO
  public Number sum (final List vals) throws CGException {
    Number varRes_2 = null;
    if (vals.size() == 0) 
      varRes_2 = new Double(0);
    else 
      varRes_2 = new Double(UTIL.NumberToReal(vals.get(0)).doubleValue() + sum(new ArrayList(vals.subList(1, vals.size()))).doubleValue());
    return varRes_2;
  }
// ***** VDMTOOLS END Name=sum#1|List

}
;
